### ISSUE TITLE
[Bug] ErrImagePull in e2e tests

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#204]
**Describe the bug**
Sometimes during the e2e test the anchor fails, and the kind cluster behaves as if the kubecarrier images haven't been loaded into it. 

**To Reproduce**
1. make clean 
2. make e2e-test

it's some kind of race condition or other transient occurrence. 

**Expected behavior**
Works as expected

**Screenshots**

<details>
<summary>k8s master cluster</summary>
<pre>
 ▲ ~ kall          
NAMESPACE            NAME                                                      READY   STATUS             RESTARTS   AGE
kube-system          coredns-6955765f44-5mtfv                                  1/1     Running            0          4m33s
kube-system          coredns-6955765f44-98g7h                                  1/1     Running            0          4m33s
kube-system          etcd-kubecarrier-svc-1-control-plane                      1/1     Running            0          4m29s
kube-system          kindnet-sl2mw                                             1/1     Running            0          4m33s
kube-system          kube-apiserver-kubecarrier-svc-1-control-plane            1/1     Running            0          4m29s
kube-system          kube-controller-manager-kubecarrier-svc-1-control-plane   1/1     Running            0          4m28s
kube-system          kube-proxy-l4rx2                                          1/1     Running            0          4m33s
kube-system          kube-scheduler-kubecarrier-svc-1-control-plane            1/1     Running            0          4m29s
kubecarrier-system   kubecarrier-operator-manager-58d49dbb6d-zrdq8             0/1     ImagePullBackOff   0          2m43s
local-path-storage   local-path-provisioner-7745554f7f-xfrpp                   1/1     Running            0          4m33s
 ▲ ~ k describe pod -n kubecarrier-system                                              
Name:         kubecarrier-operator-manager-58d49dbb6d-zrdq8
Namespace:    kubecarrier-system
Priority:     0
Node:         kubecarrier-svc-1-control-plane/172.17.0.3
Start Time:   Thu, 13 Feb 2020 11:51:39 +0100
Labels:       control-plane=operator
              kubecarrier.io/role=operator
              pod-template-hash=58d49dbb6d
Annotations:  <none>
Status:       Pending
IP:           10.244.0.6
IPs:
  IP:           10.244.0.6
Controlled By:  ReplicaSet/kubecarrier-operator-manager-58d49dbb6d
Containers:
  manager:
    Container ID:   
    Image:          quay.io/kubecarrier/operator:master-58e8c15
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wkpxr (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-wkpxr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wkpxr
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                      Message
  ----     ------     ----                 ----                                      -------
  Normal   Scheduled  2m51s                default-scheduler                         Successfully assigned kubecarrier-system/kubecarrier-operator-manager-58d49dbb6d-zrdq8 to kubecarrier-svc-1-control-plane
  Normal   Pulling    77s (x4 over 2m50s)  kubelet, kubecarrier-svc-1-control-plane  Pulling image "quay.io/kubecarrier/operator:master-58e8c15"
  Warning  Failed     76s (x4 over 2m49s)  kubelet, kubecarrier-svc-1-control-plane  Failed to pull image "quay.io/kubecarrier/operator:master-58e8c15": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/kubecarrier/operator:master-58e8c15": failed to resolve reference "quay.io/kubecarrier/operator:master-58e8c15": quay.io/kubecarrier/operator:master-58e8c15: not found
  Warning  Failed     76s (x4 over 2m49s)  kubelet, kubecarrier-svc-1-control-plane  Error: ErrImagePull
  Warning  Failed     61s (x6 over 2m49s)  kubelet, kubecarrier-svc-1-control-plane  Error: ImagePullBackOff
  Normal   BackOff    47s (x7 over 2m49s)  kubelet, kubecarrier-svc-1-control-plane  Back-off pulling image "quay.io/kubecarrier/operator:master-58e8c15"
</pre>
</details>

<details>
<summary>k8s master cluster's control plane node:</summary>
<pre>
root@kubecarrier-1-control-plane:/tmp# crictl image
IMAGE                                      TAG                 IMAGE ID            SIZE
docker.io/kindest/kindnetd                 0.5.4               2186a1a396deb       113MB
docker.io/rancher/local-path-provisioner   v0.0.11             9d12f9848b99f       36.5MB
k8s.gcr.io/coredns                         1.6.5               70f311871ae12       41.7MB
k8s.gcr.io/debian-base                     v2.0.0              9bd6154724425       53.9MB
k8s.gcr.io/etcd                            3.4.3-0             303ce5db0e90d       290MB
k8s.gcr.io/kube-apiserver                  v1.17.0             134ad2332e042       144MB
k8s.gcr.io/kube-controller-manager         v1.17.0             7818d75a7d002       131MB
k8s.gcr.io/kube-proxy                      v1.17.0             551eaeb500fda       132MB
k8s.gcr.io/kube-scheduler                  v1.17.0             09a204f38b41d       112MB
k8s.gcr.io/pause                           3.1                 da86e6ba6ca19       746kB
quay.io/jetstack/cert-manager-cainjector   v0.13.0             70afcb14b2abe       11.3MB
quay.io/jetstack/cert-manager-controller   v0.13.0             36bcce45a11fc       14.6MB
quay.io/jetstack/cert-manager-webhook      v0.13.0             cfddaa785cc47       9.15MB
quay.io/kubecarrier/catapult               master-58e8c15      af57515bdeeed       39.1MB
quay.io/kubecarrier/elevator               master-58e8c15      71352401222db       39.4MB
quay.io/kubecarrier/ferry                  master-58e8c15      4400d337a2eae       39.1MB
quay.io/kubecarrier/manager                master-58e8c15      1c64b6eb945ab       40.3MB
quay.io/kubecarrier/operator               master-58e8c15      8f5cc0a231d1e       47.3MB
</pre>
</details>

What's weirder after running `make e2e-setup` which rebuilds and reloads images into kind cluster, the kubecarrier's operator deployment vanishes. 

**Kubernetes/Openshift Cluster**
* kind v0.7.0 go1.13.6 linux/amd64
 - OS: [e.g. iOS]: Linux odyssey 5.4.17-1-MANJARO #1 SMP PREEMPT Tue Feb 4 11:40:50 UTC 2020 x86_64 GNU/Linux
* https://github.com/kubermatic/kubecarrier/tree/58e8c1563ed52f969a35f280c8361f6e12329322

**Comment by aborilov** [comment]
looks like it's not a problem already
