### ISSUE TITLE
Investigate Extension API Server for replicated objects

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#210]
We have a number of objects object within the Kubernetes cluster, that we have to replicate into multiple namespaces.

- `TenantReferences`
- `Offerings`
- `ServiceClusterReferences`
- `ProviderReferences`

`Offerings`, `ServiceClusterReferences`, `ProviderReferences` are just "read-only" objects that inform `Tenants` about available services and meta information.
Implementing these objects as a extension api server, we could get rid of saving the same information multiple times in etcd.

`TenantReferences` are more complicated, because we rely on `Providers` to be able to change their labels, to organize them into `Catalogs`.

**Comment by thetechnick** [comment]
@nmiculinic What do you think about this issue, now that you worked on the extension apiserver prototype?

**Comment by nmiculinic** [comment]
The extension apiserver is an awesome tool for view-only objects, that is objects lacking any semantic, and are just transformation of the original object in some namespace or whatever. 

The development/understanding knowledge from single to 2nd/3rd API extension server isn't high, thus after someone figuring out how to develop for apiextension server once it's easy to implement additional functionality. Actually the biggest issue was setting the whole thing up in the first place; after the wiring is done implementing additional CRUD operations equals implementing a single interface. 

For watches, we have to be extra careful against resource leakage; that is that the underlying watch is closed after the API extension watch is no longer needed. That's the biggest drawback of read-only objects. 

What I'm not sure how API extension server behaves after using it for a long time. That is, I've only fiddled with it for a week, and we could find out some serious shortcomings in a few months/year.
