### ISSUE TITLE
[Feature] Investigate server side apply

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#271]
**Is your feature request related to a problem? Please describe.**
Many controllers concurrently update the status subresource with different condition types. For example, in the `CustromResourceDiscovery` one controller updates the `Established`, other `Discovered` and another the `Ready` condition. This leads to unnecessary resource version changes and version conflicts, that is some updates fail with `Conflicting version: out of date` which causes the object to be reconciled again for no good reason. 

**Describe the solution you'd like**
Have controllers utilize the server-side application, currently beta as of kubernetes 1.16

https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/0006-apply.md

**Describe alternatives you've considered**
Alternatively, we could split up the CRDs into more and more granular pieces, such that a single controller handles the resource itself and a different controller handling the `/status` subresource. This would lead to small CRD proliferation without meaning and it's not feasible long term.

**Comment by kwiesmueller** [comment]
Hey there,
we want to focus on making Server-Side Apply better for controllers the next release.
If you have any questions or need help investigating it for kubecarrier, feel free to get in touch.
You can find us (wg-api-expression) on the Kubernetes Slack: https://github.com/pulumi/pulumi-kubernetes/issues/1230
