### ISSUE TITLE
[Bug] CustromResourceDisovery deletion leads to stuck state

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#280]
**Describe the bug**
Upon deleting `CustromResourceDiscovery` with created CRD instances in the management cluster there are no errors, but the system gets stuck in the deadlock state (without manual intervention).

Here's what's happening. The `CustomResourceDiscovery` deletion triggers the following:

* the `Catapult` is concurrently being deleted since it has `CustromResrouceDiscovery` as its owner (Kubernetes native GC, `metadata.ownerReferences` fields )
* there's catapult's finalizer on the created internal CRD instances
* The operator clears out the catapult deployment, leading all its catapult related finalizer impossible to satisfy (including those on the created CRD instances)
* The CRD deletion process starts, and there's `customresourcecleanup.apiextensions.k8s.io` finalizer waiting for all its instances deleted before the `CustromResourceDiscovery`'s internal CRD is deleted.
* those CRDs cannot be deleted since they depend on catapult deleting base CRDs on the service cluster and then removing its finalizer
* But that isn't possible since the catapult deployment is deleted.
* All in all, a messy place to be all around. 

**To Reproduce**
1. create `CustromResourceDiscovery`
2. create `CustromResourceDiscovery` CRD instance in the management cluster 
3. delete `CustromResourceDiscovery`
4. Observe error

**Possible fixes**

* operator should check that all objects having the specific catapult finalizer are cleared before deleting its deployment (( and optionally having different finalizers per catapult deployment, thus being able differentiating between them ))
* a webhook should prevent the  `CustromResourceDiscovery` deletion if any instances are present at the moment ((probably the smartest idea))

**Comment by jiachengxu** [comment]
@nmiculinic e2e test flakiness here: https://prow.loodse.com/view/gcs/prow-dev-data/pr-logs/pull/kubermatic_kubecarrier/276/pull-kubecarrier-e2e-v1.16.4/1238438856097796099
Is it related to this?

**Comment by nmiculinic** [comment]
possibly yes
