### ISSUE TITLE
Investigate k3d for kind replacement

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#308]
**Is your feature request related to a problem? Please describe.**
During the e2e test phase we setup 2 kind clusters. This takes significant time amount, especially during iterative development cycles of `make clean && make e2e-test`

On my machine kind cluster bootstraps takes about 1 minute

k3d takes about 1 second. 

This is a tracking issue for the investigation that does k3d fits our e2e criteria.

https://github.com/rancher/k3d

**Comment by thetechnick** [comment]
Moving to icebox for now, with increasing e2e test times, by adding way more tests, there is less of a reason to make the boot up quicker.

Regardless we need to test with "real" Kubernetes at least in our pipeline, with K3S being a fork, it's hard to tell how meaningful our tests will be.
