### ISSUE TITLE
[Operator] Hard to extend operator controllers with more specific reconcile logic.

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/kubecarrier#352]
a base_reconciler was introduced in #250, and it works fine for our current components (KubeCarrier, ferry, catapult, elevator)

However, now we are going to add our new component (Tower) and makes the KubeCarrier object cluster-scoped, then the issues are coming out:
# Making KubeCarrier cluster-scoped: #329 
Once the `KubeCarrier` becomes cluster-scoped, there is no need to use our own owner handling, we can use `contrillerutil.SetControllerReference` to handle the owned objects, this lead the first issue in the base reconciler:
```
// ReconcileOwnedObjects - reconcile the objects that owned by obj
func (r *BaseReconciler) reconcileOwnedObjects(ctx context.Context, obj Component, objects []unstructured.Unstructured) (bool, error) {
	var deploymentIsReady bool
	for _, object := range objects {
...
		switch restMapping.Scope.Name() {
		case meta.RESTScopeNameNamespace:
			if err := controllerutil.SetControllerReference(obj, &object, r.Scheme); err != nil {
				return false, err
			}
		case meta.RESTScopeNameRoot:
			owner.SetOwnerReference(obj, &object, r.Scheme)
		default:
			return false, fmt.Errorf("unknown REST scope: %s", restMapping.Scope.Name())
		}
...
	}
	return deploymentIsReady, nil
}
```
In the function above, we only check if the owned object is namespaced or cluster-scoped, and then choose different owner handling methods accordingly. But for the owner object, we didn't check anything. In PR #347, I added a check to check if the owner object is cluster-scoped (KubeCarrier) by checking if the namespace is empty:
```
// ReconcileOwnedObjects - reconcile the objects that owned by obj
func (r *BaseReconciler) reconcileOwnedObjects(ctx context.Context, obj Component, objects []unstructured.Unstructured) (bool, error) {
...
		if obj.GetNamespace() == "" {
			// The owner is cluster-scoped, like KubeCarrier.
			if err := controllerutil.SetControllerReference(obj, &object, r.Scheme); err != nil {
				return false, err
			}
		} else {
			switch restMapping.Scope.Name() {
			case meta.RESTScopeNameNamespace:
				if err := controllerutil.SetControllerReference(obj, &object, r.Scheme); err != nil {
					return false, err
				}
			case meta.RESTScopeNameRoot:
				owner.SetOwnerReference(obj, &object, r.Scheme)
			default:
				return false, fmt.Errorf("unknown REST scope: %s", restMapping.Scope.Name())
			}
		}
...
	}
	return deploymentIsReady, nil
}
```
This works, but not works nicely.

# Start Tower in KubeCarrier controller #325 
The issue is even worse once we now want to introduce the `Tower` for our multi-region support. 
Now we want to have a `master` flag in KubeCarrier object:
```yaml
apiVersion: operator.kubecarrier.io/v1alpha1
kind: KubeCarrier
metadata:
  name: kubecarrier
spec:
  master: true
```
If the `master` is `true`, then the `KubeCarrier` controller will create `Tower` object, and deploy `Tower`. This is even harder to achieve in the operator base reconciler.
It can be solved by adding a checking like, if the owner is `KubeCarrier`, if it is, then starts Tower...
but this doesn't solve the issue from the root at all, and we may have more similar issues in the future when we want to add more specific reconciliation logic in the future.

# Solution
Currently, I didn't see any better solution than reverting the base_conciler back to several controllers. Although there will be some code duplications, but at the least, the code is more extendable.

**Comment by jiachengxu** [comment]
WDYT? @thetechnick @nmiculinic @aborilov

**Comment by nmiculinic** [comment]
> Once the KubeCarrier becomes cluster-scoped, there is no need to use our own owner handling, we can use contrillerutil.SetControllerReference

How does that work out since the field it sets, the `metadata.ownerReferences` assumes the same namespace? Are you intending for cluster-scope objects owning namespace scoped? Since this will not work out. From the docs:

```
// OwnerReference contains enough information to let you identify an owning
// object. An owning object must be in the same namespace as the dependent, or
// be cluster-scoped, so there is no namespace field.
```

**Comment by nmiculinic** [comment]
IMHO we should extract our owner handing logic into separate helper function which shall do the magic as needed. From the RESTMapper deduce which objects are cluster-scoped and which are namespaced-scoped. Thus use `metadata.ownerReferences` as much as possible, where the rules apply, and our own approach for everything else.

We'd also use this helper function for picking the right enqueuer too.

**Comment by jiachengxu** [comment]
> How does that work out since the field it sets, the metadata.ownerReferences assumes the same namespace? Are you intending for cluster-scope objects owning namespace scoped? Since this will not work out. From the docs:

If KubeCarrier is cluster-scoped, then it can own both namespaced objects and cluster-scoped objects.
For Kubernetes docs:
Note: Cross-namespace owner references are disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
