### ISSUE TITLE
[API server] Integrate API server CRD into the main Kubecarrier CRD

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#362]
**Is your feature request related to a problem? Please describe.**
The API Server CRD shouldn't be manually created unless strictly necessary. Thus there would be an option to specify API server configuration in the master clusters Kubecarrier CRD defining the whole installation

**Describe the solution you'd like**
* [ ] Add optionally API server CRD's spec to the kubecarrier CRD 
* [ ] The operator should mostly proxy the spec and create the respective CRD
* [ ] The API server CRD's instance status should be backpropagated to Kubecarrier CRD's instance
* [ ] in the integration test their functionality

**Comment by thetechnick** [comment]
Superseded by #446
