### ISSUE TITLE
[API server] configure ingress resource for it

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#364]
**Is your feature request related to a problem? Please describe.**
The operator should also create the ingress resource if it was specified in the API server CRD

**Describe the solution you'd like**
* [ ] Add optionally ingress configuration to the API server CRD. 
* [ ] The operator should mostly proxy the ingress spec and create the respective ingress resource
* [ ] in the integration test their functionality

**Comment by thetechnick** [comment]
We don't want to configure ingress objects via our operator, as there are too many options (different Ingress Controllers, Istio, Linkerd) and deployment scenarios.

Superseded by #446
