### ISSUE TITLE
 [API server] Add API Server support in SUT debugging utility

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#385]
Currently, the SUT has issues with debugging the API server. The issue is as following. The API server starts and with its OIDC discovery configuration, it's connecting to `dex.kubecarrier.svc` which isn't resolvable outside kind cluster, that is the DNS cannot perform its job. 

For this solution investigate how the telepresence usually does things for enabling processes resolving cluster DNS entries (it's probably starting the process in the right Linux namespaces) and replicate that in the IDE configurations.

**Comment by thetechnick** [comment]
Does this still apply, when we have https://github.com/kubermatic/kubecarrier/issues/447?

I would also like to start a concept discussion about our CLI and the SUT utility.
I think we have to select, if this is development tooling or something that people can use for normal debugging.
Currently the only (well) documented usage of the CLI is the installation of KubeCarrier.
