### ISSUE TITLE
API Server - Instance Endpoint

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#419]
The (service) instance endpoint provides access to CRUD operations for arbitrary service instances (CRD instances) offered to a tenant.

As this API endpoint has to deal with dynamic object types, the URL also needs to incorporate an extensive mandatory option list:
e.g. `/api/v1/accounts/{account}/instances/{instanceType}/{instanceVersion}/{name}`

## Questions/Solution List:

**How to encode arbitrary objects in protobuf?**
-> Wrapper Object with a Byte-Payload and a Encoding field. Encoding defaults to JSON for the beginning.

**Handling multiple CRD versions**
-> URL parameter and usage of the appropriate k8s object version (likely via unstructured.Unstructured)

**Proposed Protobuf Schema**
TBD

**Comment by nmiculinic** [comment]
>  e.g. /api/v1/account/{account}/instances/{instanceType}/{instanceVersion}/{name}

btw, we should have a consistent noun plurality; what I've found online it's usually recommended having plural form, i.e. `/api/v1/accounts` not `/api/v1/account` 

( e.g. one of the recommendation https://nordicapis.com/10-best-practices-for-naming-api-endpoints/  )

Maybe we should pick some style guide we're following in that?

**Comment by thetechnick** [comment]
Yeah, was a typo - is fixed now

**Comment by thetechnick** [comment]
From the daily:
- `ClusterRole` and `RoleBinding` for the api-server (to have the right to create these objects) will be managed by the `DerivedCR` controller in the main controller manager.
- `DerivedCR` objects are unready until the Role is bound

**Comment by thetechnick** [comment]
implemented in #424 
/close
